          <div class="row">
          	  <br><br>
          	<div class="col-md-4 col-md-offset-4 text-center">
          	   <h4 class="text-muted"> &copy; Todos los derechos reservados  <?php echo date("Y"); ?></h4>
          	</div>
          </div>
    </section>
    <script src="<?php echo $assets_js; ?>jquery-1.12.4.min.js"></script>
	<script src="<?php echo $assets_js; ?>bootstrap.min.js"></script>
</body>
</html>